ALTER TABLE media_import_v1 ADD COLUMN type VARCHAR(32) NOT NULL DEFAULT 'IMAGE';
ALTER TABLE media_import_v1 ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE media_import_v1 ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE media_import_v1 ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE media_import_v1 ADD COLUMN version INTEGER NOT NULL DEFAULT 1;