micronaut:
  server:
    port: ${SERVER_PORT:8080}
  application:
    name: hm-grunndata-import
    thread-selection: auto
  executors:
    consumer:
      type: fixed
      nThreads: 1
  security:
    redirect:
      enabled: false
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SECRET:MustBeAVeryLongSecretAndUsedThisForTestImportOnly}
              jws-algorithm: HS256
  metrics:
    enabled: true
    sensitive: false
    binders:
      uptime:
        enabled: true
      processor:
        enabled: true
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

endpoints:
  metrics:
    enabled: true
    sensitive: false
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

datasources:
  default:
    url: ${DB_JDBC_URL:`jdbc:tc:postgresql:14:///gdb?TC_INITSCRIPT=file:src/test/resources/postgres/postgres-init.sql`}
    driverClassName: ${DB_DRIVER:org.testcontainers.jdbc.ContainerDatabaseDriver}
    username: ${DB_USERNAME:import}
    password: ${DB_PASSWORD:import}
    maximum-pool-size: 8
    minimum-idle: 0
    pool-name: default

flyway:
  datasources:
    default:
      locations: classpath:db

rapidsandrivers:
  enabled: ${RAPIDSANDRIVERS_ENABLED:false}

kafka:
  topic: teamdigihot.hm-grunndata-v1
  consumerGroupId: hm-grunndata-register-g1
  trustStorePath: ${KAFKA_TRUSTSTORE_PATH:}
  trustStorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  keystorePath: ${KAFKA_KEYSTORE_PATH:}
  keystorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  health:
    enabled: false
