micronaut:
  server:
    port: ${SERVER_PORT:8080}
    context-path: /import
  http:
    client:
      connect-timeout: 10s
      read-timeout: 60s
      event-loop-group: http
  netty:
    event-loops:
      http:
        num-threads: 25
        prefer-native-transport: true
  caches:
    suppliers:
      charset: 'UTF-8'
    series:
      charset: 'UTF-8'
    agreements:
      charset: 'UTF-8'
      expire-after-write: 1d
  application:
    name: hm-grunndata-import
    thread-selection: auto
  executors:
    consumer:
      type: fixed
      nThreads: 1
  security:
    enabled: true
    redirect:
      enabled: false
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
    token:
      bearer:
        enabled: true
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SECRET:MustBeAVeryLongSecretAndUsedThisForTestImportOnly}
              jws-algorithm: HS256
  metrics:
    enabled: true
    sensitive: false
    binders:
      uptime:
        enabled: true
      processor:
        enabled: true
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

endpoints:
  metrics:
    enabled: true
    sensitive: false
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

datasources:
  default:
    url: ${DB_JDBC_URL:`jdbc:tc:postgresql:14:///importapi?TC_TMPFS=/testtmpfs:rw&TC_INITSCRIPT=file:src/test/resources/postgres/postgres-init.sql&TC_REUSABLE=true`}
    driverClassName: ${DB_DRIVER:org.testcontainers.jdbc.ContainerDatabaseDriver}
    username: ${DB_USERNAME:importapi}
    password: ${DB_PASSWORD:importapi}
    maximum-pool-size: 8
    minimum-idle: 0
    pool-name: default

flyway:
  datasources:
    default:
      locations: classpath:db
      clean-on-validation-error: true # only during dev and poc, will remove when we go to production.
      clean-schema: true

rapidsandrivers:
  enabled: ${RAPIDSANDRIVERS_ENABLED:false}

kafka:
  topic: teamdigihot.hm-grunndata-v1
  consumerGroupId: hm-grunndata-import-g1
  trustStorePath: ${KAFKA_TRUSTSTORE_PATH:}
  trustStorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  keystorePath: ${KAFKA_KEYSTORE_PATH:}
  keystorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  health:
    enabled: false

schedulers:
  enabled: ${SCHEDULERS_ENABLED:false}

grunndata:
  db:
    url: ${GRUNNDATA_DB_URL:`http://localhost:8888`}

media:
  upload:
    url: ${MEDIA_UPLOAD_URL:`http://localhost:8081/api/v1/upload/media/import`}